
version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    environment:
      - spring.data.elasticsearch.cluster-nodes=elasticsearch:9300
      - spring.data.elasticsearch.cluster-name=docker-cluster