version: '3.3'
services:
  redis:
    image: redis:latest
    ports:
    - '6379':'6379'
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'newdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'okan10189'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'okan10189'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-newdb:/var/lib/mysql
# Names our volume
volumes:
  my-newdb: